### ISSUE TITLE
Typeahead removes spaces

### ISSUE THREAD

**Issue by svet007** [mgcrea/angular-strap#1604] opened 2015-03-25 19:46 UTC
http://mgcrea.github.io/angular-strap/#/typeaheads#typeaheads

Type "fasdfasd asdfasdfas" quickly in the Address typeahead. You can type any two sequences of letters, separated by space

Expected: "fasdfasd asdfasdfas" in the typeahead field

Actual "fasdfasdasdfasdfas" in the typeahead field (space removed)

**Comment by andremetzen** [comment] 2015-03-29 17:53
Same issue here.

**Comment by vmlf01** [comment] 2015-04-05 06:41
Might be fixed with PR #1439?

**Comment by albertldlan** [comment] 2015-04-11 02:20
Not sure if this has been addressed or not, but the space can be somewhat retained if you wait a bit before entering the next sequence of characters. So in your example, if you typed "fasdfasd asdfasdfas" in a smooth sequence it would return as "fasdfasdasdfasdfas", but if you typed "fasdfasd", waited for a few seconds, then hit space and typed "asdfasdfas", you would get "fasdfasd asdfasdfas," as expected. It's definitely not ideal and a weird issue.

This is on 2.2.1, the latest available version on bower.

**Comment by jindalsyogesh** [comment] 2015-06-05 20:31
I just download v2.2.4 from bower and I am facing the same issue. Any update on when it will be fixed?

**Comment by mgcrea** [comment] 2015-06-06 19:46
Use the `trimValue` option landed in #1439

**Closed by mgcrea** 2015-06-06 19:46 UTC
Labels: directive-typeahead

**Comment by daniel-nalbach** [comment] 2015-06-25 22:49
I see the trimValue code in the 2.2.4 source but am still experiencing the space trimming issue after updating from 2.0.5 to 2.2.4 like jindalsyogesh mentioned. 

Looking at the code, I believe the problem is that in line 157 the watchOptions code is still using trim() on the match parsing. So trimValue will not work if also using watchOptions.  :(

**Comment by jindalsyogesh** [comment] 2015-06-26 21:02
daniel-nalbach, I used the following two attributes on my input box and it worked on version 2.2.4: 
data-trim-value="false" ng-trim="false"

**Comment by qqilihq** [comment] 2016-10-25 11:15
Can confirm this, `data-trim-value="false"` alone didn't suffice, adding `ng-trim="false"` works. Thank you, @jindalsyogesh.

If that's the intention that both attributes need to be added, it should be documented like this.

**Comment by iceboxX** [comment] 2017-08-16 09:50
It was working very weirdly, this fixed however `data-trim-value="false" ng-trim="false"`.
Thanks
