### ISSUE TITLE
positioning popover via service

### ISSUE THREAD

**Issue by DealerCorp** [mgcrea/angular-strap#1609] opened 2015-03-30 18:45 UTC
after upgrade to 2.2.1, my popover positions went wrong.
even the sample on angular-strap, the popover is not positioned correctly. 
![image](https://cloud.githubusercontent.com/assets/8525800/6903927/6bf9d364-d6eb-11e4-8ccb-52e1158ab15d.png)

**Comment by etiennejsnippets** [comment] 2015-05-28 21:27
+1

**Comment by kamekazemaster** [comment] 2015-06-12 14:49
+1

**Comment by DanielSchuech** [comment] 2015-06-12 14:49
+1

**Comment by phymous** [comment] 2015-06-12 14:56
Worked better in v2.0.1:
![auswahl_066](https://cloud.githubusercontent.com/assets/7686856/8132703/e77fef1a-1123-11e5-88f1-6b77260a4040.png)

**Comment by AzadMemon** [comment] 2015-07-23 16:09
Not to badger you, but +1 for me as well.

**Comment by evillemez** [comment] 2015-08-15 22:01
+1 Same... does anyone know what specifically changed?

**Comment by sebastientromp** [comment] 2015-10-12 07:40
+1

**Comment by vmlf01** [comment] 2015-11-01 15:38
duplicate of #1566

**Closed by vmlf01** 2015-11-01 15:38 UTC
Labels: directive-popover, duplicate
