### ISSUE TITLE
Tooltips not appearing in ui-grid cell template

### ISSUE THREAD

**Issue by ocsike** [mgcrea/angular-strap#1944] opened 2015-11-05 13:40 UTC
Hi,
The tooltip must be showing when the input get focus.
The tooltip showing when outside the grid, but when it is inside the grid it not shows. No error or something happened. 

Here is the plunker http://plnkr.co/edit/rHlAmRe7Z5TxfHIqRBTq?p=preview

**Comment by vmlf01** [comment] 2015-11-05 21:56
Duplicate of #1132 
Please see my comment there

**Closed by vmlf01** 2015-11-05 21:56 UTC
Labels: directive-tooltip, duplicate
