### ISSUE TITLE
Modal.show throwing an error if HTML contains comments!

### ISSUE THREAD

**Issue by bumblebeeman** [mgcrea/angular-strap#1628] opened 2015-04-04 17:06 UTC
Just spotted this bug, if the HTML of a modal contains comments, I am getting the following error:

> Cannot set property 'display' of undefined

I discovered this after copying and pasting the modal example from the twitter bootstrap site. Works fine when I delete the comments, throws this error if I don't.

I am on AngularStrap 2.2.1

**Comment by vmlf01** [comment] 2015-04-04 22:11
Maybe related to #492?

**Comment by mgwidmann** [comment] 2015-06-05 17:42
:+1: hit by this bug by putting an `ngIf` at the first line of the template (which creates a comment).

**Comment by tomnielsen** [comment] 2015-09-15 05:41
Ran into this bug first time I tried to follow a tutorial. Not a great experience.

Offending code:
```javascript
// Focus once the enter-animation has started
// Weird PhantomJS bug hack
var el = modalElement[0];
requestAnimationFrame(function() {
  el.focus();
});
```

```focus``` is undefined for html comment element. 
> el.nodeName
"#comment"

Fixing this crash can be as simple as:
```javascript
  if (typeof el.focus != 'undefined') {
    el.focus();
  }
```
But the real question is why these elements are being matched.

**Comment by vmlf01** [comment] 2015-11-10 16:57
Duplicate of #492

**Closed by vmlf01** 2015-11-10 16:57 UTC
Labels: directive-modal, duplicate, needs-test-case
