### ISSUE TITLE
Display datepicker inline without input element

### ISSUE THREAD

**Issue by slavafomin** [mgcrea/angular-strap#1019] opened 2014-08-29 17:50 UTC
Hi!

Thanks for this great library!

I'm trying to use DatePicker directive in my project that is not using Bootstrap at all. So we are in the middle of re-creating styles to display this widget correctly.

Is it possible to render this widget inline (not as a popup) inside of a DIV for example, without using any input elements at all? It will really help with styling and such. Or is it possible to at least prevent popup from closing?

Thanks!

**Comment by jacobvalenta** [comment] 2015-01-25 03:23
+1

I wanted to place two date pickers side by side. In a high use area, minimizing the need to click would be nice.

**Comment by toymachiner62** [comment] 2015-04-20 23:18
:+1:

**Comment by rzschech** [comment] 2015-05-13 12:48
This is a duplicate of #430

**Closed** 2015-05-13 13:19 UTC
Labels: directive-datepicker, duplicate, enhancement, question, review-future
