### ISSUE TITLE
Skip all leading non-node elements in compiler

### ISSUE THREAD

**Issue by wingedfox** [mgcrea/angular-strap#1844] opened 2015-08-27 12:42 UTC
This code
```js
var templateEl = angular.element(templates[0]);
var contentEl = findElement('[ng-bind="content"]', templateEl[0]).removeAttr('ng-bind').html(templates[1]);
```
takes the very first element despite the fact that it might be non-node element.
I met this issue when customer asked me to add copyright block to all the templates, which made it look like
```js
templateEl = [
 comment,
 text,
 div.modal.modal-confirm
]
length: 3
```

**Comment by vmlf01** [comment] 2015-11-10 16:58
Duplicate of #492

**Closed by vmlf01** 2015-11-10 16:58 UTC
Labels: duplicate
