### ISSUE TITLE
Angular expressions as input element values breaks button groups

### ISSUE THREAD

**Issue by Mihail-K** [mgcrea/angular-strap#1720] opened 2015-06-04 14:37 UTC
Using angular expressions in the value attribute of input elements in a button group (say, populated by ngRepeat) causes an error and breaks the button group.

Here's a plunker link to demo the issue. http://plnkr.co/edit/Mta9g2Iui7xPWlo0vJiD?p=preview

```
Error: [$parse:syntax] Syntax Error: Token '{' is not a valid identifier at column 7 of the expression [model.{{ day }}] starting at [{{ day }}].
```

**Comment by vmlf01** [comment] 2015-06-04 19:51
Duplicate of #501

**Closed by vmlf01** 2015-06-04 19:51 UTC
Labels: directive-buttons, duplicate
