### ISSUE TITLE
Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by Maangs** [mgcrea/angular-strap#1864] opened 2015-09-14 11:11 UTC
So I'm facing the problem caused by using both Angular-strap and Angular-ui.
Is there any solution for this yet?

![tolower](https://cloud.githubusercontent.com/assets/12379444/9848517/1c615c98-5ae2-11e5-865f-27683d2323e1.PNG)

**Comment by TheSpy** [comment] 2015-09-24 12:50
that's a conflict with ui-bootstrap, most likely $tooltip or similar, i believe it's going to be fixed within the next version https://github.com/mgcrea/angular-strap/commit/7776d8c7c59f6dc3c6c8d9ab0ad7841a920416ec

**Comment by a5hik** [comment] 2015-10-16 12:42
Hi I'm facing the same issue. when the fix will be available or the next release is planned?

**Comment by TheSpy** [comment] 2015-10-16 13:01
for now i just did "replace all" with prefix bs, eg. $tooltip with $bsTooltip in angular-strap.min.js and it works :-)

**Comment by vmlf01** [comment] 2015-11-08 09:23
Looks like you need to include ```angular-strap.compat.js``` or ```angular-strap.compat.min.js``` file instead of ```angular-strap.js``` for the change in 7776d8c to work, but other than that, it should already work with latest release version.

Can anyone please confirm that it works?

**Comment by vmlf01** [comment] 2015-11-08 09:26
Duplicate of #521

**Closed** 2015-11-08 09:29 UTC
