### ISSUE TITLE
Angular strap modal popup does not showing the background

### ISSUE THREAD

**Issue by grrseguin** [mgcrea/angular-strap#1445] opened 2015-01-19 11:51 UTC
Hi,

I'm using angular-strap (v 2.1.6) with bootstrap css. When i'm using Modals, the background is not showing because of wrong CSS style in bootstrap v 3.3.1.

To fix it, i am using bootstrap v 3.2.0.

Therefore, i suggest to remove the caret in the bower.json file.

Example : http://jsfiddle.net/1hgkmwxe/ Vs http://jsfiddle.net/by3rph5s/

**Comment by samherrmann** [comment] 2015-01-28 20:57
I experienced the same issue and @grrseguin 's solution worked for me as well

**Comment by vmlf01** [comment] 2015-02-11 21:16
Duplicate of #1263

**Closed by vmlf01** 2015-02-11 21:16 UTC
Labels: directive-modal
