### ISSUE TITLE
bs-typeahead auto select first option issue - 2.2.0

### ISSUE THREAD

**Issue by peteringram0** [mgcrea/angular-strap#1586] opened 2015-03-19 10:37 UTC
If you upgrade from an earlier option to get typeahead to auto select the first option available you now need to specify auto-select="true" as part of the directive.

Please can this also be added to the docs as it fails to mention this.

**Comment by ansonkao** [comment] 2015-03-19 18:38
Hey there. The docs have been updated but haven't been deployed - the live site is still showing 2.1.6. Bower also needs to get updated.

**Comment by ansonkao** [comment] 2015-03-19 18:52
Duplicate of #1585

**Comment by peteringram0** [comment] 2015-03-19 20:24
thanks

**Closed** 2015-04-16 19:18 UTC
Labels: directive-typeahead, docs
