### ISSUE TITLE
Modals dialogs allow tabbing into the background document.

### ISSUE THREAD

**Issue by MihaiBalint** [mgcrea/angular-strap#1697] opened 2015-05-19 09:00 UTC
A modal dialog should restring tab cycling to the modal content rather than the whole document.

Easily reproduced on http://mgcrea.github.io/angular-strap/#/modals by clicking to open the modal and then using the tab key repeatedly until focus is given to elements behind the modal.

**Comment by andras-tim** [comment] 2015-05-19 10:48
+1

**Comment by vmlf01** [comment] 2015-05-19 10:48
Duplicate of #839

**Closed by vmlf01** 2015-05-19 10:48 UTC
Labels: directive-modal, duplicate
