### ISSUE TITLE
Modal dialog allows tab navigation in background

### ISSUE THREAD

**Issue by wingedfox** [mgcrea/angular-strap#1238] opened 2014-11-06 12:34 UTC
Issue is reproducible on the demo page.
Steps:
1. Open http://mgcrea.github.io/angular-strap/ demo page
2. Open modal dialog
3. Press "Tab" key several times
Expected result:
Tab changes focused items within the modal dialog only
Actual result:
Focus leaves modal dialog and allows to scroll page, activate links, etc

**Comment by vmlf01** [comment] 2015-05-19 10:48
Duplicate of #839

**Closed by vmlf01** 2015-05-19 10:48 UTC
Labels: directive-modal, duplicate, enhancement, needs-investigation, possible-bug
