### ISSUE TITLE
Close modal on browser back

### ISSUE THREAD

**Issue by Creo** [mgcrea/angular-strap#864] opened 2014-06-30 07:24 UTC
When a modal dialog is open and the user click the browser back button, the modal is still displayed but the user is unable to perform any action. 

What is the recommended way to close all modal dialogs when the user navigates by changing the URL?

One way I can think of is to maintain a global list where all modals are registered, and then listen to the locationChangeStart event on rootScope, where we loop through the list and close all modals that have been registered in the list.

Another approach would be to add
```
$rootScope.$on('$locationChangeStart', function() {
    $modal.destroy();
});
```
directly in the modal provider in angular-strap.js

Is there a better way to do it?

**Comment by 09star** [comment] 2015-05-22 02:13
same problem @spencerwi  

 after trigger $hide() , I navigate to another page ,  and can't scroll the page any more. 

any way to solve this problem ?
@mgcrea

**Comment by b1rdex** [comment] 2015-05-22 03:01
@09star looks like the only way is using some $timeout before navigating to be sure modal becomes hidden.

**Comment by vijender1256** [comment] 2015-07-27 18:28
//Used to close the modal popups on back button click earlier we had issues with state management on back button click
app.run(['$rootScope', '$modalStack', function ($rootScope, $modalStack) {
    /*
       If you are using ui-router, use $stateChangeStart method otherwise use $locationChangeStart
       StateChangeStart will trigger as soon as the user clicks browser back button or keyboard backspace and modal will be removed from modal stack
    */
    $rootScope.$on('$stateChangeStart', function (event) {
        var top = $modalStack.getTop();
        if (top) {
            $modalStack.dismiss(top.key);
        }
    })
}]);

**Comment by henry74** [comment] 2015-09-21 16:26
@vijender1256 are you sure$modalStack is available for the ngStrap library?  I think this is only for Angular-ui which is a different library.

**Comment by strizzaflex** [comment] 2015-09-21 19:32
Am I wrong that the methods for dealing with this where they are listening for modal events is only good if you don't prefix your modal events. I think you should be prefixing them to avoid issues. The other thought here is that back button is ment to pop off the stack and go back as you would expect. Can this not just be solved by adding:  
if(evt.which === 8 && $modal.$isShown){
            $modal.hide();
          }

to the $modal.$onKeyUp function? This will just navigate to the previous state and remove the modal at the same time, no? If this is what people are looking for I can put in a pull request. We have the same requirement to do this where I work and I was going to just fork the project an implement the change. But like I said if this is what people want then it's like 3 lines of code.

**Comment by henry74** [comment] 2015-09-21 19:39
@strizzaflex what about the situation where a user is re-directed after a timeout back to the login page; there is no user interaction in this situation.

**Comment by strizzaflex** [comment] 2015-09-21 19:53
@henry74 That is true but the title of this tread is specific to hitting the back no? It would be better to have a modal manager that kept track of modals based on url location. if you wanted to have a modal that spanned multiple locations you could pass that in and if it's specific to a location or relative location then it could manage it's life cycle. This is with popover and alert as well. I think it should be addressed in the same way to fix all three.

**Comment by henry74** [comment] 2015-09-21 20:01
Yes, title doesn't apply.  Just providing more situations where a fix should address all situations driven by a route change which is the root cause of this issue.  The $scope variable is destroy upon a route change so the $modal handles for hiding/closing are no longer available which leaves a modal on the user's screen without the ability to close it down.

**Comment by andras-tim** [comment] 2015-09-22 09:07
:+1: for https://github.com/mgcrea/angular-strap/issues/864#issuecomment-62595002

*I can say some situation, where same modal have to use after Back/Forward.*

**Comment by strizzaflex** [comment] 2015-10-02 11:29
I agree that it should be an option and defaulted to off. However, there are going to be times when this comes up and QA is not going to want a modal or popover or whatever to be floating in it's same position on another page out of context with with the other elements. I tried to solve this with a modal manager that lives outside of angular strap but it would either force me to implement the manager everywhere i use a modal or popover or force me to create a constructor for those types of objects that would hand me back a modal created using the manager and there would be ways around either. I'm going to try adding it into angular strap and see what it looks like. I'll post what i do back here for comments.

**Comment by dmitry-dedukhin** [comment] 2015-12-08 13:13
Taking into account that modal events could be prefixed, there is no any reliable workaround to close opened modals programatically.
I think [this](https://github.com/mgcrea/angular-strap/issues/864#issuecomment-54101267) is a good proposal.

**Comment by ondrejchmelar** [comment] 2015-12-22 13:37
+1

**Comment by kimx** [comment] 2016-03-23 08:28
Inject the $modalStack service and call the function $modalStack.dismissAll()
http://stackoverflow.com/questions/25445949/how-to-close-angular-ui-modal-from-anywhere

**Comment by dmitry-dedukhin** [comment] 2016-03-23 11:00
@kimx, you are talking about angular-ui, but this issue relates to angular-strap.

**Comment by vijender1256** [comment] 2016-03-23 13:11
The solution that i gave works for angular-ui, but i am not sure if it works for angular-strap.

**Comment by kimx** [comment] 2016-03-23 13:32
@dmitry-dedukhin  An oversight.I apologize.

**Closed** 2016-04-02 22:08 UTC
Labels: directive-modal, enhancement, review-future
