### ISSUE TITLE
Select: Form tab navigation not working in IE, Chrome

### ISSUE THREAD

**Issue by aplamon** [mgcrea/angular-strap#1666] opened 2015-04-28 07:29 UTC
Version 2.2.1
In latest version of Chrome and IE the tab behavior is not working. When tabbing to the select it opens the dropdown. Another tab closes the dropdown. Then hitting tab again the tab focus is lost altogether in the form. Next tab gives focus to the first item in the form. Works on FF though.

**Comment by vmlf01** [comment] 2015-04-28 09:11
Looks like duplicate of #1557

**Comment by aplamon** [comment] 2015-04-30 06:26
Yeah, duplicate

**Closed** 2015-04-30 06:25 UTC
Labels: directive-select
