### ISSUE TITLE
Backdrop for modal with Bootstrap 3.3.1 won't show

### ISSUE THREAD

**Issue by denishavranek** [mgcrea/angular-strap#1398] opened 2015-01-05 14:31 UTC
http://plnkr.co/edit/rETlWmijehgSP1MaKS96?p=preview

The backdrop modal is in the DOM, but has no height assigned and it seems, that the backdrop isn't there.

Also the z-index acts weird and some elements show over the backdrop.

This last thing happens also with 3.3.0

**Comment by vmlf01** [comment] 2015-01-05 23:15
Duplicate of #1263 and #1381

**Closed by vmlf01** 2015-01-05 23:15 UTC
Labels: directive-modal, duplicate
