### ISSUE TITLE
Bootstrap dropdown is not working when used with angular strap popover(bs-popover)

### ISSUE THREAD

**Issue by Harshini-D** [mgcrea/angular-strap#1478] opened 2015-01-29 17:24 UTC
The template for angular strap popover used is filter.tpl.html.
In the popover template, I added bootstrap dropdown by just appending data-toggle="dropdown" for a button.
On click of the button, the dropdown is not working.
The same button is working when used on plain html.
Example:
![dropdownissue](https://cloud.githubusercontent.com/assets/10756626/5962409/c0ab8aa8-a809-11e4-829d-72c03e0f0fb7.jpg)

**Comment by vmlf01** [comment] 2015-01-29 20:00
Are you including both Angular-strap and Bootstrap js at the same time?

**Comment by Harshini-D** [comment] 2015-01-30 08:51
Yes, in the popover ( which is angular strap) I have used bootstrap drop down. So its a kind of using both at the same time.

**Comment by vmlf01** [comment] 2015-02-11 21:11
Duplicate of #521

**Closed by vmlf01** 2015-02-11 21:11 UTC
