### ISSUE TITLE
Edit in Plunkr is broken

### ISSUE THREAD

**Issue by gweax** [mgcrea/angular-strap#1704] opened 2015-05-21 08:56 UTC
Every "edit in Plunk" functionality on http://mgcrea.github.io/angular-strap is broken. The plunkr is opened, but due to a script error nothing works.

    Error: [$injector:modulerr] http://errors.angularjs.org/1.3.8/$injector/modulerr?p0=mgcrea.ngStrapDocs&p1=%5B%24injector%3Amodulerr%5D%20http%3A%2F%2Ferrors.angularjs.org%2F1.3.8%2F%24injector%2Fmodulerr%3Fp0%3Dmgcrea.ngStrap%26p1%3D%255B%2524injector%253Anomod%255D%2520http%253A%252F%252Ferrors.angularjs.org%252F1.3.8%252F%2524injector%252Fnomod%253Fp0%253Dmgcrea.ngStrap%250AT%252F%253C%2540http%253A%252F%252Fcode.angularjs.org%252F1.3.8%252Fangular.min.js%253A6%253A416%250AOd%252F%253C%252F%253C%252F%253C%2540http%253A%252F%252Fcode.angularjs.org%252F1.3.8%252Fangular.min.js%253A21%253A366%250Aa%2540http%253A%252F%252Fcode.angularjs.org%252F1.3.8%252Fangular.min.js%253A21%253A7%250AOd%252F%253C%252F%253C%2540http%253A%252F%252Fcode.angularjs.org%252F1.3.8%252Fangular.min.js%253A21%253A1%250Ag%252F%253C%2540http%253A%252F%252Fcode.angularjs.org%252F1.3.8%252Fangular.min.js%253A35%253A354%250As%2540http%253A%252F%252Fcode.angularjs.org%252F1.3.8%252Fangular.min.js%253A7%253A300%250Ag%2540http%253A%252F%252Fcode.angularjs.org%252F1.3.8%252Fangular.min.js%253A35%253A202%250Ag%252F%253C%2540http%253A%252F%252Fcode.angularjs.org%252F1.3.8%252Fangular.min.js%253A35%253A371%250As%2540http%253A%252F%252Fcode.angularjs.org%252F1.3.8%252Fangular.min.js%253A7%253A300%250Ag%2540http%253A%252F%252Fcode.angularjs.org%252F1.3.8%252Fangular.min.js%253A35%253A202%250AOb%2540http%253A%252F%252Fcode.angularjs.org%252F1.3.8%252Fangular.min.js%253A38%253A435%250Asc%252Fd%2540http%253A%252F%252Fcode.angularjs.org%252F1.3.8%252Fangular.min.js%253A17%253A350%250Asc%2540http%253A%252F%252Fcode.angularjs.org%252F1.3.8%252Fangular.min.js%253A18%253A153%250AJd%2540http%253A%252F%252Fcode.angularjs.org%252F1.3.8%252Fangular.min.js%253A16%253A483%250A%2540http%253A%252F%252Fcode.angularjs.org%252F1.3.8%252Fangular.min.js%253A249%253A412%250Aa%2540http%253A%252F%252Fcode.angularjs.org%252F1.3.8%252Fangular.min.js%253A164%253A354%250Alf%252Fc%2540http%253A%252F%252Fcode.angularjs.org%252F1.3.8%252Fangular.min.js%253A32%253A358%250A%0AT%2F%3C%40http%3A%2F%2Fcode.angularjs.org%2F1.3.8%2Fangular.min.js%3A6%3A416%0Ag%2F%3C%40http%3A%2F%2Fcode.angularjs.org%2F1.3.8%2Fangular.min.js%3A36%3A98%0As%40http%3A%2F%2Fcode.angularjs.org%2F1.3.8%2Fangular.min.js%3A7%3A300%0Ag%40http%3A%2F%2Fcode.angularjs.org%2F1.3.8%2Fangular.min.js%3A35%3A202%0Ag%2F%3C%40http%3A%2F%2Fcode.angularjs.org%2F1.3.8%2Fangular.min.js%3A35%3A371%0As%40http%3A%2F%2Fcode.angularjs.org%2F1.3.8%2Fangular.min.js%3A7%3A300%0Ag%40http%3A%2F%2Fcode.angularjs.org%2F1.3.8%2Fangular.min.js%3A35%3A202%0AOb%40http%3A%2F%2Fcode.angularjs.org%2F1.3.8%2Fangular.min.js%3A38%3A435%0Asc%2Fd%40http%3A%2F%2Fcode.angularjs.org%2F1.3.8%2Fangular.min.js%3A17%3A350%0Asc%40http%3A%2F%2Fcode.angularjs.org%2F1.3.8%2Fangular.min.js%3A18%3A153%0AJd%40http%3A%2F%2Fcode.angularjs.org%2F1.3.8%2Fangular.min.js%3A16%3A483%0A%40http%3A%2F%2Fcode.angularjs.org%2F1.3.8%2Fangular.min.js%3A249%3A412%0Aa%40http%3A%2F%2Fcode.angularjs.org%2F1.3.8%2Fangular.min.js%3A164%3A354%0Alf%2Fc%40http%3A%2F%2Fcode.angularjs.org%2F1.3.8%2Fangular.min.js%3A32%3A358%0A

**Comment by vmlf01** [comment] 2015-05-21 11:15
Duplicate of #1660

**Closed by vmlf01** 2015-05-21 11:15 UTC
Labels: duplicate
