### ISSUE TITLE
Error is thrown with the asynchronous usage of typeahead with angular 1.4.0

### ISSUE THREAD

**Issue by capaj** [mgcrea/angular-strap#1710] opened 2015-05-27 16:36 UTC
Try the asynchronous typeahead with angular 1.4.0 and you should get this error.
```
Error: [filter:notarray] Expected array but received: {}
http://errors.angularjs.org/1.4.0/filter/notarray?p0=%7B%7D
    at REGEX_STRING_REGEXP (http://localhost:3000/jspm_packages/github/angular/bower-angular@1.4.0/angular.js:71:12)
    at http://localhost:3000/jspm_packages/github/angular/bower-angular@1.4.0/angular.js:18114:31
    at fn (eval at <anonymous> (unknown source), <anonymous>:2:459)
    at Object.$get.$parseOptions.valuesFn (http://localhost:3000/app/components/typeahead/parse-options.js:28:24)
    at Object.fn (http://localhost:3000/app/components/typeahead/typeahead.js:170:23)
    at Scope.$get.Scope.$digest (http://localhost:3000/jspm_packages/github/angular/bower-angular@1.4.0/angular.js:15559:29)
    at Scope.$get.Scope.$apply (http://localhost:3000/jspm_packages/github/angular/bower-angular@1.4.0/angular.js:15827:24)
    at done (http://localhost:3000/jspm_packages/github/angular/bower-angular@1.4.0/angular.js:10266:47)
    at completeRequest (http://localhost:3000/jspm_packages/github/angular/bower-angular@1.4.0/angular.js:10438:7)
    at XMLHttpRequest.requestLoaded (http://localhost:3000/jspm_packages/github/angular/bower-angular@1.4.0/angular.js:10379:9)angular.js:12224 (anonymous function)angular.js:9058 $getangular.js:15577 $get.Scope.$digestangular.js:15827 $get.Scope.$applyangular.js:10266 doneangular.js:10438 completeRequestangular.js:10379 requestLoaded

```

**Comment by capaj** [comment] 2015-05-27 17:14
this is the reason: https://github.com/angular/angular.js/pull/10352

**Comment by vmlf01** [comment] 2015-05-27 17:21
Duplicate of https://github.com/mgcrea/angular-strap/issues/1567

**Closed by vmlf01** 2015-05-27 17:21 UTC
Labels: angular-1.4, directive-typeahead, duplicate
