### ISSUE TITLE
bad positioning of popover

### ISSUE THREAD

**Issue by Jisay** [mgcrea/angular-strap#1904] opened 2015-10-07 08:58 UTC
Hi,

On the example page (http://mgcrea.github.io/angular-strap/#/popovers) the last example (using $popover service) is not well positioned. 

I reproduce the bug and I find that it is due to the show method of tooltip factory. When using show option on popover, it's well positioned. It's because in init(), there is a $scope.$$postDigest and in show(), there is no $scope.$$postDigest.

Not sure it's the best solution but it resolves the problem. Can you fix this ?

**Comment by jarinwhite** [comment] 2015-10-16 04:17
+1

**Comment by vmlf01** [comment] 2015-11-01 15:38
duplicate of #1566

**Closed by vmlf01** 2015-11-01 15:38 UTC
Labels: directive-popover, duplicate
