### ISSUE TITLE
Conflict between angular-strap and AngularUI Bootstrap using bs-select

### ISSUE THREAD

**Issue by dlwhiteman** [mgcrea/angular-strap#1446] opened 2015-01-19 17:22 UTC
I am using both this library and UI Bootstrap (https://github.com/angular-ui/bootstrap) together.  When I use the select support in angular-strap with UI Bootstrap also loaded, I receive JavaScript errors.  The reason for this is that both libraries provide a $tooltip() function.  When I change the order of the directives, it just changes where the exception is thrown.  When the ui-bootstrap directive appears after angular-strap, I get an exception here in line 2997 of angular-strap.js when using the bs-select: `$select = $tooltip(element, options);`, because of the same-named function in ui-bootstrap.

**Comment by vmlf01** [comment] 2015-01-19 19:36
Duplicate of #521

**Closed by vmlf01** 2015-01-19 19:36 UTC
