### ISSUE TITLE
Compatibility with UI Bootstrap

### ISSUE THREAD

**Issue by jontayesp** [mgcrea/angular-strap#521] opened 2014-03-04 20:22 UTC
If I load the angular-strap module alongside the "ui.bootstrap" module, several javascript errors are reported and components do not work. Ideally, it would be great to mix and match the best components from both libraries.

The UI Bootstrap library can be found here: http://angular-ui.github.io/bootstrap/

**Comment by ClearCloud8** [comment] 2015-01-20 16:57
+1

**Comment by siulung4073** [comment] 2015-03-03 18:12
+1

**Comment by ryancat** [comment] 2015-04-08 21:46
+1

**Comment by grepnull** [comment] 2015-04-18 02:43
+1

**Comment by Florelli** [comment] 2015-05-25 13:18
Same as @jsanders here !

Restricting myself to version 2.1.6 of angular-strap and including only the modules of bootstrap.ui that I'm using solved the issue.

**Comment by gaui** [comment] 2015-06-17 16:55
+1. I'm using Angular-Strap in conjunction with UI-Bootstrap and having conflicts between $modal. Was there some solution to this?

**Comment by ryancat** [comment] 2015-06-17 18:36
@gaui We are having same issue here. For now there is no clean way to resolve this as angular is resolving injectable providers using a internal key-value pair based on names. Our temporarily solution is using a static angular ui bootstrap library, and duplicate the ```$modal``` provider with a new name ```$uimodal```. As long as angular strap loads after angular ui bootstrap, you can always use ```$modal``` for angular strap, and ```$uimodal``` for angular ui bootstrap. 

It's essentially not a good practice to use both library as they are not promising compatibility.

**Comment by gaui** [comment] 2015-06-17 18:38
@ryancat Not a viable solution. This makes it hard to upgrade ui-bootstrap.

All directives are prefixed with `bs` - why not factories/services also? So it would be `$bsModal` or something.

**Comment by ryancat** [comment] 2015-06-17 19:13
@gaui Even with bs prefix, conflicts may happen in the future of angular ui bootstrap. Angular team may also use bs prefix in their next version of library (I have seen on their github page but cannot find it now).

**Comment by gaui** [comment] 2015-06-17 19:26
@ryancat Yes but there is an obvious conflict currently. The `bs` prefix was just a suggestion, because they have it in their directives. It can be `as` or whatever, I don't care. I just don't want Angular-Strap to conflict with ui-bootstrap. :)

**Comment by ryancat** [comment] 2015-06-17 19:39
haha sure -- I was working on unifying our third party libraries used in our front end codebase. The ```modal``` provider is just one of that. We were using old version of angular strap and manually changed some code for date picker. Now it's impossible to upgrade it without regression, sigh...

**Comment by gaui** [comment] 2015-06-17 20:08
Hehe, that's exactly what I'm trying to avoid. :smile:

**Comment by cemeng** [comment] 2015-07-16 05:59
Thanks to @mgcrea work on integrating angular-material compiler in 2.3.0, it's now trivial to implement a modal provider that has similar API as ui-bootstrap modal in angular-strap.

Here's a gist of such implementation I've done for our project: https://gist.github.com/cemeng/6a1cb617581f7b71f47f - with this you'd only need to change $modal references to Modal on your codebase and that's it.

**Comment by frapontillo** [comment] 2015-09-23 06:58
@mgcrea are there news on this? I can help out if we define a way to solve this.

**Comment by mgcrea** [comment] 2015-09-23 08:54
The compat was ruled out since it could not be fully automated (eg. inline attribute ref from directive name). We could rename every service to `$bsTooltip` for the next minor. But that would break all setups. And I don't really want to bump a major over this.

**Comment by oliversalzburg** [comment] 2015-09-23 08:59
> Also, angular2 is around the corner and will properly address this.
That still leaves all the angular 1.x users without a solution though :(

**Comment by frapontillo** [comment] 2015-09-23 09:03
Can't you ship a compatibility version alongside the main one?

**Comment by mgcrea** [comment] 2015-09-23 09:05
I could, but the issue is that it could not easily be automated (mostly due to inline refs). But it could be done. Unfortunately, I don't really have the time to spend a couple of hours on this for now.

**Comment by frapontillo** [comment] 2015-09-23 09:19
If you could provide some guidelines on the procedure you have in mind I could do that and open a PR here.

**Comment by e-cloud** [comment] 2015-09-23 09:26
one of my gulp task is to use ngAnnotate to rename the some service
```
    fix_angular_strap: function () {
		return gulp.src(bower_dir+'/angular-strap/dist/angular-strap.js')
			.pipe(gulp.plugins.ngAnnotate({
				add: true,
				remove: true,
				rename: [
					{from: '$tooltip', to: '$asTooltip'},
					{from: '$button', to: '$asButton'},
					{from: '$modal', to: '$asModal'}]
			}))
			.pipe(gulp.dest(bower_dir+'/angular-strap/fix'))
	},
```
@frapontillo if you don't know how to refactor, you can use ngAnnotate to rename the service, and then  take diff compare, then you will know where to rename/refactor

**Comment by mgcrea** [comment] 2015-09-23 09:28
We could use something like @e-cloud to produce a gulp build prefixing all services with `bs`, renaming directives from `bs` to `as` would break due to inline refs such as : https://github.com/mgcrea/angular-strap/blob/master/src/modal/modal.js#L344

**Comment by frapontillo** [comment] 2015-09-23 09:34
@e-cloud yes, I implemented the `rename` feature for `ngAnnotate` to address this very issue :smile:.

Deal @mgcrea, if you're willing to bundle the compat build (something like `dist/angular-strap.compat.js` plus the `min` file?) I will get this done.

**Comment by mgcrea** [comment] 2015-09-23 09:41
@frapontillo sounds good to me, just poc'd this in 7776d8c7c59f6dc3c6c8d9ab0ad7841a920416ec. Feel free to iterate upon the current master & test it.

**Comment by frapontillo** [comment] 2015-09-23 10:11
:+1:

**Comment by mgcrea** [comment] 2015-09-24 18:04
A compat build landed in d063b44. Released in `v2.3.3`.

Thanks!

**Closed by mgcrea** 2015-09-24 18:04 UTC
Labels: directive-modal, directive-popover, directive-tooltip, enhancement, needs-work

**Comment by frapontillo** [comment] 2015-09-24 18:11
![https://media.giphy.com/media/Quietv6CIsWkw/giphy.gif]()

**Comment by jontayesp** [comment] 2015-09-24 18:16
:heart:

**Comment by michaelgli** [comment] 2015-09-29 20:07
I'm loading it this way:
    <script type="text/javascript" src="./manual-download/angular-strap.compat.js"></script>
    <script type="text/javascript" src="./manual-download/angular-strap.tpl.js"></script>
    <script type="text/javascript" src="./bower_components/angular-bootstrap/ui-bootstrap-tpls.js"></script>

But I got this error:
Unknown provider: $$bsRAFProvider <- $$bsRAF <- $bsTooltip <- $bsTypeahead <- bsTypeaheadDirective <- $bsTooltip

I'm using it like the following:
<div class="form-group">
    <label>Icon</label>
    <input type="text" class="form-control" ng-model="selectedIcon" data-min-length="0" data-html="1" data-auto-select="true" data-animation="am-flip-x" bs-options="icon as icon.label for icon in icons" placeholder="Enter icon" bs-typeahead>
</div>

Am I missing something?

Thanks,
-michael

**Comment by frapontillo** [comment] 2015-09-29 20:08
Yeah, I f***ed up a renaming, it's already been fixed in master.
Sorry fellas!

On Tue, Sep 29, 2015, 10:07 PM michaelgli <notifications@github.com> wrote:

> I'm loading it this way:
>
>
> But I got this error:
> Unknown provider: $$bsRAFProvider <- $$bsRAF <- $bsTooltip <- $bsTypeahead
> <- bsTypeaheadDirective <- $bsTooltip
>
> I'm using it like the following:
> Icon
>
> Am I missing something?
>
> Thanks,
> -michael
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mgcrea/angular-strap/issues/521#issuecomment-144176031>
> .
>
-- 
Francesco Pontillo

**Comment by blah238** [comment] 2015-10-13 21:01
@frapontillo @mgcrea can we get a release with https://github.com/mgcrea/angular-strap/commit/847d938bc60882dfb0a032d5e73d7c6b141ef243?

**Comment by javierfvargas** [comment] 2015-10-14 14:34
+1

**Comment by frapontillo** [comment] 2015-10-15 09:49
@blah238 it's not up to me, pinging @mgcrea for this :smile:

**Comment by javierfvargas** [comment] 2015-10-26 17:31
Guys I'm having some problems using together angular-strap and ui-bootstrap (most recent versions).  In some cases it is just some errors in the debug console but in others it is angular-strap getting unusable depending on the inclusion order.

Check this plunker.

http://plnkr.co/edit/QAA6mxfCV88QQPSUadUt

Hope it is useful.

**Comment by just-boris** [comment] 2015-10-26 19:29
You should add `angular-strap.compat.js` build to get this resolved. See the updated plunk: http://plnkr.co/edit/9s3KYmEcIHoMpNt5R8X1?p=preview

**Comment by javierfvargas** [comment] 2015-10-26 20:02
@just-boris thanks, it fixes it.  Is this compat build something temporal or it is going to be this way now on?
FYI ui-bootstrap guys are also fixing it, now their master branch does not have this kind of issue.
http://plnkr.co/edit/QAA6mxfCV88QQPSUadUt

**Comment by Astoico** [comment] 2017-04-26 14:19
I am here to say that if you are reading this, and have both the compat and regular versions of the angular-strap.js and are still getting the console error, You may be using `bs-tooltip` in your code which you should change to `uib-tooltip`
