### ISSUE TITLE
Popover arrow points wrong

### ISSUE THREAD

**Issue by bastrapp** [mgcrea/angular-strap#1747] opened 2015-06-24 15:13 UTC
Since a short time in Chrome and Safari and for a longer time already in Firefox the pointer of a popover on the side either points to high or to low. Even on your example page (the one at the right):
http://mgcrea.github.io/angular-strap/#popovers

**Comment by vmlf01** [comment] 2015-11-01 15:37
duplicate of #1566

**Closed by vmlf01** 2015-11-01 15:37 UTC
Labels: directive-popover, duplicate
