### ISSUE TITLE
Typeahead not working with AngularJS 1.4.0 properly

### ISSUE THREAD

**Issue by mbates** [mgcrea/angular-strap#1728] opened 2015-06-10 18:37 UTC
On my project the typeahead list is placed above the the top of the page. On the plunker demo linked from here http://mgcrea.github.io/angular-strap/#/typeaheads, when I stop plunker and change angular from 1.3.15 to 1.4.0, the typeahead replaces elements in the list with what you are matching. Type "califor" to see what I mean.

**Comment by safjanowski** [comment] 2015-06-15 12:52
Some stack trace when we are trying to use `Angular 1.4` with `typeahead` plugin

```javascript
Error: [filter:notarray] Expected array but received: {}
http://errors.angularjs.org/1.4.0/filter/notarray?p0=%7B%7D
    at REGEX_STRING_REGEXP (http://localhost:3000/bower_components/angular/angular.js:68:12)
    at http://localhost:3000/bower_components/angular/angular.js:18111:31
    at fn (eval at <anonymous> (http://localhost:3000/bower_components/angular/angular.js:13036:15), <anonymous>:2:535)
    at Object.$get.$parseOptions.valuesFn (http://localhost:3000/javascripts/app.js:57:26)
    at Object.fn (http://localhost:3000/bower_components/angular-strap/dist/angular-strap.js:3898:25)
    at Scope.$get.Scope.$digest (http://localhost:3000/bower_components/angular/angular.js:15556:29)
    at Scope.$get.Scope.$apply (http://localhost:3000/bower_components/angular/angular.js:15824:24)
    at bootstrapApply (http://localhost:3000/bower_components/angular/angular.js:1628:15)
    at Object.invoke (http://localhost:3000/bower_components/angular/angular.js:4426:17)
    at doBootstrap (http://localhost:3000/bower_components/angular/angular.js:1626:14)
```

**Comment by vmlf01** [comment] 2015-06-15 13:07
From the stack trace, maybe duplicate of #1567?

**Comment by palortoff** [comment] 2015-07-07 11:52
The `Error: [filter:notarray]` belongs to the `Address (async via maps.googleapis.com)` input.
If you remove that input from the plunker the error will no longer occur.

The state typeahead will still not work (reproduced with angular 1.4.2).
When clicking into the input field while it is empty the typeahead popup will not show when you start typing.
When the input field is not empty when giving it the focus, the typeahead popup will show.

However, if you add `data-min-length="0"` the popup will open on focus and update while typing.

**Closed** 2015-07-12 22:50 UTC
Labels: angular-1.4, directive-typeahead
