### ISSUE TITLE
Angular 1.4 support

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [mgcrea/angular-strap#1659] opened 2015-04-23 13:13 UTC
When do you guys plan to support 1.4
I have included 1.4 to my project and with your typeahead i get error after clicking couple of times on it:

TypeError: options.domOperation is not a function
    at close (angular-animate.js:2747)
    at angular-animate.js:2566
    at forEach (angular.js:332)
    at angular-animate.js:2560
    at Scope.$get.Scope.$digest (angular.js:15352)
    at safeDigest (angular-strap.js:5211)
    at angular.module.provider.$get.$tooltip.show (angular-strap.js:4742)
    at Object.angular.module.provider.$get.$typeahead.show (angular-strap.js:4380)
    at HTMLInputElement.angular.module.provider.$get.$tooltip.enter (angular-strap.js:4682)
    at HTMLInputElement.n.event.dispatch (jquery-2.1.1.min.js:3)

**Comment by vmlf01** [comment] 2015-04-24 07:11
Got that also when trying a plunker with modals, so it might not be specific to typeahead. We need to test it more to find out the causes.

**Comment by homerjam** [comment] 2015-04-28 22:52
Angular 1.4 contains breaking changes relating to ngAnimate, some more detail [here](https://github.com/angular/angular.js/blob/master/CHANGELOG.md#v140-rc0-smooth-unwinding-2015-04-10)

**Comment by mgcrea** [comment] 2015-05-20 10:33
Fixed by afd4fc71b66b95422abaf1e47509027914bbced0.

**Closed by mgcrea** 2015-05-20 10:33 UTC
Labels: angular-1.4, needs-investigation

**Comment by mgcrea** [comment] 2015-05-20 10:35
There is still a couple of typeahead issues before 1.4 compat, I've added `gulp karma:travis~1.4.0` to test again the current rc.
