### ISSUE TITLE
Question: datepicker not setting the date

### ISSUE THREAD

**Issue by paulflo150** [mgcrea/angular-strap#1464] opened 2015-01-24 19:37 UTC
What am I doing wrong here:

<code>
module.directive('tesDatepicker', ['$datepicker', '$filter', function ($datepicker, $filter) {return {

            restrict: 'A',
            replace: true,
            require: 'ngModel',
            scope: {
                elementModel: '=',
                minDate: '=',
                maxDate: '=',
                issmall: '=',
                placeholder: '@',
                required: '='
            },
            templateUrl: 'views/templates/formcontrols/tes.datepicker.html',
            link: function (scope, element, attrs, ctrl) {
                scope.myDatepicker = $datepicker(element, ctrl, { scope: scope, trigger: 'manual', autoclose: true, dateFormat: 'MM/dd/yyyy' });
                scope.open = function ($event) {                                       
                    if (scope.myDatepicker.$isShown)
                        scope.myDatepicker.hide();
                    else
                        scope.myDatepicker.show();
                    console.log(scope.myDatepicker.$isShown);
                };
            },
        };
</code>

When the dropdown opens for the very first time, it is empy, and the date is not formatted:

![empty](https://cloud.githubusercontent.com/assets/8136504/5888651/33a7a59c-a3d6-11e4-927d-ee3549b2834d.png)

Clicking on the arrows brings up the calendar, however the date selected does not get selected in the calendar, although the model does get updated.

Any ideas?

**Comment by vmlf01** [comment] 2015-01-24 20:19
Duplicate of #1436

**Closed by vmlf01** 2015-01-24 20:19 UTC
Labels: directive-datepicker, duplicate
